section: screens
	fat-laptop:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		preserveFocus = false
		switchCorners = none 
		switchCornerSize = 0
	vcg-jlu2-mac.attlocal.net:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		preserveFocus = false
		switchCorners = none 
		switchCornerSize = 0
end

section: aliases
end

section: links
	fat-laptop:
		right = vcg-jlu2-mac.attlocal.net
	vcg-jlu2-mac.attlocal.net:
		left = fat-laptop
end

section: options
	relativeMouseMoves = false
	screenSaverSync = false
	win32KeepForeground = false
	clipboardSharing = true
	clipboardSharingSize = 100000000
	switchCorners = none 
	switchCornerSize = 0
	keystroke(BackSpace) = lockCursorToScreen(toggle)
end


